spring:
    application:
        name: suns-gateway

server:
    port: 8103

zuul:
    host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000

    ignored-services: "*"   #滤服务之间通信附带的headers
    sensitiveHeaders: "*"   #过滤客户端附带的headers
#    prefix: /api #为zuul设置一个公共的前缀
    routes:
        auth:
            path: /auth/**
            serviceId: suns-auth
        server-user:
            path: /admin/**
            serviceId: suns-server-admin
        server-core:
            path: /core/**
            serviceId: suns-server-core

    add-proxy-headers: true


security:
    validate:
        code: false
    sessions: stateless
    oauth2:
        resource:
            loadBalanced: true
            user-info-uri: http://suns-auth/user
            prefer-token-info: false
            service-id: suns-gateway

urls:
    anon:
        - /mobile/**
        - /auth/**

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000