spring:
    application:
        name: suns-gateway

    thymeleaf:
        prefi: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        cache: false


server:
    port: 8103

zuul:
    ignored-services: "*"   #滤服务之间通信附带的headers
    sensitiveHeaders: "*"   #过滤客户端附带的headers
#    prefix: /api #为zuul设置一个公共的前缀
    routes:
        auth:
            path: /auth/**
            serviceId: suns-sso-auth
        server-user:
            path: /user/**
            serviceId: suns-server-user
        server-core:
            path: /core/**
            serviceId: suns-server-core

    add-proxy-headers: true


jwt:
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key