spring:
    application:
        name: suns-auth

    redis:
        host: 127.0.0.1
        port: 6379
        remote: true        #cachecloud 获取

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://qdm162290194.my3w.com:3306/qdm162290194_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&tinyInt1isBit=false
        username: ENC(01ez0Rw8at261C++9qdM3z0TyG/GQGSb)
        password: ENC(J+kOB2WIhdln1nm9qPizPquichN6hL2T)

server:
    port: 8201

urls:
    anon:
        - /form/**
        - /signup
        - /social
        - /mobile/token

suns:
    auth:
        clientId: ryan
        clientSecret: ryanSecret
        scope: server
    social:
        qq:
            providerId: qq
            clientId: 252f7eb688ceca204c50
            clientSecret: ef0616fa5f3f54263cb11d6c369efb240ef5da2f