spring:
    application:
        name: suns-server-auth

    redis:
        host: 127.0.0.1
        port: 6379

    thymeleaf:
        prefi: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        cache: false
        mode: LEGACYHTML5
server:
    port: 8201
    ssl:
        enabled: false


ryan:
    suns:
        auth:
            loginUrl: "/login"
            successUrl: "/index"
            unauthorizedUrl: "/403"
