spring:
    application:
        name: suns-server-auth

    redis:
        host: 127.0.0.1
        port: 6379

server:
    port: 8201
    ssl:
        enabled: false


ryan:
    suns:
        auth:
            loginUrl: "/login"
            successUrl: "/index"
            unauthorizedUrl: "/403"
