spring:
    application:
        name: suns-sso-auth
    profiles:
          active: ${SPRING_PROFILES_ACTIVE:dev}
    redis:
        host: 127.0.0.1
        port: 6379

    thymeleaf:
        prefi: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        cache: false

server:
    port: 8201

security:
    basic:
        enabled: false
    oauth2:
        resource:
            filter-order: 3


